// The browser inference must reproduce what the Python backend (xgboost + pred_contribs) produced for the
// same inputs. demo-data.json is generated by scripts/export_ml_demo.py from the real trained model.
/* global process */
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { loadModel, predictMargin, predictProba, shap } from './xgb';

const read = (f) => JSON.parse(readFileSync(resolve(process.cwd(), 'public/ml-data', f), 'utf8'));
const model = loadModel(read('triage_model.json'));
const demo = read('demo-data.json');
const FEATURES = demo.models.triage.features;

describe('browser XGBoost matches the backend', () => {
  for (const s of demo.samples.triage) {
    const x = FEATURES.map((f) => s.input[f]);
    it(`probability: ${s.title}`, () => {
      expect(predictProba(model, x)).toBeCloseTo(s.output.probability, 3);
    });
    it(`TreeSHAP: ${s.title}`, () => {
      const phi = shap(model, x);
      for (const t of s.output.top_features) expect(phi[FEATURES.indexOf(t.feature)]).toBeCloseTo(t.contribution, 3);
      expect(model.bias).toBeCloseTo(s.output.base_value, 3);
      // local accuracy: contributions + bias reproduce the margin exactly
      expect(phi.reduce((a, b) => a + b, 0) + model.bias).toBeCloseTo(predictMargin(model, x), 6);
    });
  }
});
