"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-21 02:10:57.753225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_ip'), ['ip'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('blocklist',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('removed_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocklist_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocklist_ip'), ['ip'], unique=True)

    op.create_table('iocs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value')
    )
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iocs_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_iocs_value'), ['value'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_incident_id'), ['incident_id'], unique=False)

    op.create_table('playbooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbooks_name'), ['name'], unique=True)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('asset_links',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('src_id', sa.String(length=32), nullable=False),
    sa.Column('dst_id', sa.String(length=32), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src_id', 'dst_id', 'protocol', 'port')
    )
    with op.batch_alter_table('asset_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_links_dst_id'), ['dst_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_links_src_id'), ['src_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_breakdown', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('primary_source_ip', sa.String(length=64), nullable=True),
    sa.Column('primary_host', sa.String(length=255), nullable=True),
    sa.Column('primary_user', sa.String(length=128), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('first_event_at', sa.DateTime(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('assignee_id', sa.String(length=32), nullable=True),
    sa.Column('auto_handled', sa.Boolean(), nullable=False),
    sa.Column('report_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_last_event_at'), ['last_event_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_incidents_primary_host'), ['primary_host'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_primary_source_ip'), ['primary_source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('threat_intel',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ioc_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threat_intel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threat_intel_ioc_id'), ['ioc_id'], unique=False)

    op.create_table('analyst_actions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyst_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyst_actions_incident_id'), ['incident_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('destination_ip', sa.String(length=64), nullable=True),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('destination_host', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('process', sa.String(length=255), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_events_incident_ts', ['incident_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source_host'), ['source_host'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_source_ip'), ['source_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_username'), ['username'], unique=False)

    op.create_table('incident_iocs',
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('ioc_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ioc_id'], ['iocs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'ioc_id')
    )
    op.create_table('mitre_mappings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('tactic', sa.String(length=64), nullable=False),
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('technique_name', sa.String(length=128), nullable=False),
    sa.Column('subtechnique', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'technique_id', 'source')
    )
    with op.batch_alter_table('mitre_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mitre_mappings_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mitre_mappings_technique_id'), ['technique_id'], unique=False)

    op.create_table('model_predictions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('prediction', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_predictions_kind'), ['kind'], unique=False)

    op.create_table('playbook_executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('playbook_name', sa.String(length=96), nullable=False),
    sa.Column('playbook_version', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playbook_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playbook_executions_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbook_executions_playbook_name'), ['playbook_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_playbook_executions_status'), ['status'], unique=False)

    op.create_table('timeline_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_entries_incident_id'), ['incident_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=True),
    sa.Column('step_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['playbook_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('execution_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('approval_mode', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('rollback', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['playbook_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_steps_execution_id'), ['execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_steps_execution_id'))

    op.drop_table('execution_steps')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_incident_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_entries_incident_id'))

    op.drop_table('timeline_entries')
    with op.batch_alter_table('playbook_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbook_executions_status'))
        batch_op.drop_index(batch_op.f('ix_playbook_executions_playbook_name'))
        batch_op.drop_index(batch_op.f('ix_playbook_executions_incident_id'))

    op.drop_table('playbook_executions')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_kind'))
        batch_op.drop_index(batch_op.f('ix_model_predictions_incident_id'))

    op.drop_table('model_predictions')
    with op.batch_alter_table('mitre_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mitre_mappings_technique_id'))
        batch_op.drop_index(batch_op.f('ix_mitre_mappings_incident_id'))

    op.drop_table('mitre_mappings')
    op.drop_table('incident_iocs')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_username'))
        batch_op.drop_index(batch_op.f('ix_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_events_source_ip'))
        batch_op.drop_index(batch_op.f('ix_events_source_host'))
        batch_op.drop_index(batch_op.f('ix_events_source'))
        batch_op.drop_index('ix_events_incident_ts')
        batch_op.drop_index(batch_op.f('ix_events_incident_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_event_id'))

    op.drop_table('events')
    with op.batch_alter_table('analyst_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyst_actions_incident_id'))

    op.drop_table('analyst_actions')
    with op.batch_alter_table('threat_intel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threat_intel_ioc_id'))

    op.drop_table('threat_intel')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_source'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_primary_source_ip'))
        batch_op.drop_index(batch_op.f('ix_incidents_primary_host'))
        batch_op.drop_index(batch_op.f('ix_incidents_number'))
        batch_op.drop_index(batch_op.f('ix_incidents_last_event_at'))

    op.drop_table('incidents')
    with op.batch_alter_table('asset_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_links_src_id'))
        batch_op.drop_index(batch_op.f('ix_asset_links_dst_id'))

    op.drop_table('asset_links')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('revoked_tokens')
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playbooks_name'))

    op.drop_table('playbooks')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_incident_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('iocs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iocs_value'))
        batch_op.drop_index(batch_op.f('ix_iocs_type'))

    op.drop_table('iocs')
    with op.batch_alter_table('blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocklist_ip'))
        batch_op.drop_index(batch_op.f('ix_blocklist_active'))

    op.drop_table('blocklist')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_ip'))
        batch_op.drop_index(batch_op.f('ix_assets_hostname'))

    op.drop_table('assets')
    # ### end Alembic commands ###
