"""Training corpus for the phishing text model.

Hand-written examples (the original 100 plus a few with links added so that a link alone is not
treated as a phishing signal). Small and template-like: cross-validation scores on it are inflated
by that similarity and must not be read as real-world accuracy.
"""

PHISHING_EMAILS = [
    'Dear employee, the CEO has requested an immediate wire transfer of $50,000 to vendor account.', "Hi, I'm the new CFO. Please process this invoice payment urgently. Do not discuss with others.", 'CEO Office: Please process reimbursement for my travel expenses attached. Handle personally.',
    'I need you to purchase gift cards for a client meeting today. Keep this confidential.',
    'Accounts Payable: Please update the vendor bank details to the following new account.',
    'This is the Managing Director. I need an urgent bank transfer of $35,000 processed today.',
    'Please wire $28,000 to the attached account. This is confidential and time-sensitive. - CEO', "Can you process a payment for me? I'm in a meeting and can't call. Need it done in 30 mins.", 'The board approved bonuses. Send me a list of employee bank details for direct deposit.',
    'As discussed on our call, please transfer $42,000 to the new supplier account immediately.',
    'URGENT: Your account has been compromised. Click here immediately to reset your password.',
    'IT Department: Your mailbox is full. Verify your credentials within 24 hours or lose access.',
    'Action required: Suspicious login detected. Confirm your identity now to avoid account lockout.',
    'Microsoft 365: Your subscription is expiring. Renew immediately to avoid service disruption.',
    'Warning: Your email account will be deactivated unless you confirm your password today.',
    'IT Security: Mandatory password change required within 2 hours. Use this link.',
    'Your Google Workspace session has expired. Re-authenticate now to restore access.',
    'Zoom alert: Your meeting recordings will be deleted in 24 hours. Login to save them.',
    'Office 365: Multiple failed sign-in attempts. Secure your account immediately.',
    'Slack notification: Your workspace admin requires you to verify your account.',
    'Confidential: Salary adjustment notification. Login to HR portal to accept new terms.',
    'HR Department: Your tax documents are ready. Download them using your company credentials.',
    'IMPORTANT: Board meeting rescheduled. Download the updated agenda from this secure link.',
    'Your performance review results are available. Access the HR portal to view your rating.',
    'Annual bonus confirmation attached. Open the secure PDF to verify your compensation.',
    'Employee satisfaction survey results are in. Click here to see how your team scored.',
    'Your package could not be delivered. Click the link to update your shipping information immediately.',
    'FedEx: Delivery failed. Reschedule your delivery by confirming your address here.', "Amazon: Your order #4829 has been placed. If this wasn't you, click here to cancel.", 'Netflix: Your payment method has failed. Update your billing info to avoid suspension.',
    'Apple: Your iCloud storage is almost full. Upgrade now or risk losing your photos.',
    'DHL: A package is waiting for customs clearance. Pay the $2.99 fee to release it.',
    'Security alert: Someone tried to access your account from Russia. Verify your identity now.',
    'Bank of America: Unusual activity detected on your account. Login now to secure your funds.',
    'Your DocuSign document is ready for signature. Click here to review and sign immediately.',
    'Windows Defender: Critical threat detected on your PC. Call this number immediately.',
    'Your antivirus subscription has expired. Your device is at risk. Renew now.',
    'PayPal: We noticed unusual activity. Verify your identity or your account will be limited.',
    'Urgent payment reminder: Transfer the outstanding balance immediately to avoid penalties.',
    'Please review the attached invoice and authorize payment before end of business today.',
    'Your Dropbox shared folder access is expiring. Re-authenticate to keep your files.',
    'LinkedIn: Someone viewed your profile from an unrecognized device. Secure your account.',
    'Instagram: We detected a login from a new device. Click here to verify it was you.',
    'WhatsApp: Your account registration code is about to expire. Enter it now.',
    'Twitter/X Security: Unusual activity detected. Change your password immediately.',
    'Outlook Web App: Your session will expire in 15 minutes. Click here to stay signed in.',
    'Adobe Creative Cloud: License violation detected. Verify your subscription now.', "Coinbase: Withdrawal of 2.5 BTC initiated. If this wasn't you, cancel immediately.", 'Your PayPal account is limited. Confirm your identity at http://paypa1-secure-login.top/verify within 24 hours or it will be closed.',
    'Microsoft 365 password expires today. Keep your password: http://185.234.72.19/o365/login now.',
    'DHL: Your parcel is held. Pay the customs fee at https://bit.ly/3xYzAbC immediately to release delivery.',
    'Dear customer, unusual sign-in detected. Verify your Apple ID at http://apple-id-verify.xyz/account urgently.',
    'IT Helpdesk: mailbox quota exceeded. Re-validate your login at http://mail-quota-update.click/login to avoid deactivation.',
    'Docusign: You have a document awaiting signature. Review at http://docusign-secure.work/review immediately.',
    'Your bank card was suspended. Restore access now: http://secure-bankofamerica-login.top/restore', "CEO here. I'm in a meeting. Buy gift cards and send me the codes at this link http://gift-request.tk/submit now.", 'Netflix: payment declined. Update billing at http://netflix-billing-update.ml/pay or your account will be suspended today.',
    'Security alert: your password was compromised. Reset it at http://185.10.68.4/reset right away.']

LEGITIMATE_EMAILS = [
    'Hi team, just a reminder about our weekly standup meeting tomorrow at 10 AM.',
    'The quarterly report has been published on the shared drive. Please review at your convenience.',
    'Congratulations to the sales team for exceeding Q3 targets! Great work everyone.',
    'Reminder: Office will be closed next Monday for the holiday. Enjoy the long weekend.',
    'The new employee handbook has been updated. You can find it on the company intranet.',
    'Team lunch this Friday at noon. Please let me know your dietary preferences.', "Project update: We've completed the first phase of the migration. Details in attached doc.", 'Happy birthday, Sarah! Cake in the break room at 3 PM.',
    'Please submit your timesheets by end of day Friday. Thank you.',
    'FYI - the conference room on the 3rd floor will be under maintenance next week.',
    'The new software license has been approved. IT will begin installation on Monday.', "Sharing the meeting notes from today's product review. Action items highlighted in yellow.", 'Reminder to complete the annual compliance training by the end of the month.',
    'Great presentation today! The client was very impressed with the demo.',
    'Welcome aboard, Mike! Looking forward to working with you on the infrastructure team.',
    'Attached are the design mockups for the new dashboard. Feedback welcome.',
    'The firmware update for the office printers has been completed. No action needed.',
    'Our annual company picnic is scheduled for August 15th. RSVP on the events page.',
    'Meeting cancelled: The vendor postponed the demo to next Thursday. Calendar updated.',
    'The parking lot will be repaved this weekend. Please use the side entrance on Monday.',
    'Sprint retrospective notes are attached. Main action item: improve test coverage.',
    'The client signed off on the design. We can proceed to the development phase.',
    'Deployment to staging is complete. Please run your smoke tests when convenient.',
    'Here are the API documentation updates from the last release. Review at your leisure.',
    'Database migration will happen this Saturday from 2-4 AM. No action needed from your side.',
    'The accessibility audit results look great. Only minor issues in the footer component.',
    'Open enrollment for health insurance begins next month. Details on the benefits portal.',
    'The company town hall is scheduled for next Wednesday at 2 PM. Attendance is optional.',
    'New parking passes are available at the front desk. Pick yours up this week.',
    'Flu shot clinic will be in Conference Room B next Tuesday from 10 AM to 2 PM.',
    'The recycling program has been expanded. New bins are in the kitchen area.',
    'Reminder: Submit your PTO requests for December by the end of this month.', "Who's interested in joining the company softball team this season? Sign up by Friday.", 'The coffee machine on the 4th floor is fixed! Back to our regular brew.',
    'Photos from the holiday party have been uploaded to the shared album. Great memories!',
    'Does anyone have recommendations for a good Italian restaurant near the office?',
    'Lost and found: A blue umbrella was left in the lobby. Claim it at reception.', "The book club meets next Thursday. We're reading 'Atomic Habits' by James Clear.", 'Thank you for attending our webinar. Here are the slides as promised.',
    'Your annual support contract has been renewed. No action required on your end.', "We've published our monthly product newsletter. Check out the new features.", 'Meeting confirmed for Tuesday at 3 PM. Looking forward to discussing the partnership.',
    'The workshop materials are available on our portal. Access credentials unchanged.',
    'Thanks for your order. Estimated delivery is next Wednesday. Tracking link attached.',
    'Your subscription renewal has been processed. Receipt attached for your records.',
    'Invoice #3847 has been paid. Thank you for the prompt processing.',
    'The quarterly business review presentation is attached. See you Thursday.',
    'Conference registration is confirmed. Hotel block info will follow next week.',
    'Your GitHub pull request #482 was merged. View it at https://github.com/acme/app/pull/482',
    'Reminder: the all-hands recording is available at https://intranet.acme.com/videos/all-hands.',
    'Your Zoom meeting starts in 10 minutes. Join at https://acme.zoom.us/j/123456789 - see you there.',
    'Invoice INV-2291 from Contoso Ltd is attached. View online at https://billing.contoso.com/invoices/2291.',
    'Your order has shipped. Track it at https://www.amazon.com/gp/your-account/order-details. Thanks for shopping.',
    'The design review notes are in Confluence: https://acme.atlassian.net/wiki/spaces/DES/pages/1234.',
    'Please review the updated security policy on the intranet: https://intranet.acme.com/policies/security.', "Your Google Calendar event 'Sprint planning' was updated. https://calendar.google.com/calendar/event", 'Slack digest: 3 unread messages in #engineering. Open https://acme.slack.com/archives/C024 to read.',
    'Your monthly statement is ready in the online banking portal you normally use. No action is required.',
    'Thanks for registering for the webinar. Add it to your calendar: https://events.acme.com/webinar/42',
    'Build #1834 passed on main. Details: https://ci.acme.com/builds/1834',
    'Your library book is due Friday. Renew at https://library.city.gov/account if you need more time.',
    'Release notes for v2.4 are published at https://docs.acme.com/releases/2.4 - no upgrade action needed.',
    'Welcome to the team! Your onboarding checklist is at https://intranet.acme.com/onboarding.']
